version: "3.9"
services:
  mysql-container-devops:
    image: "mysql"
    container_name: mysql-container-devops
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stationSki
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - devops-network
    volumes:
      - mysql-data:/var/lib/mysql

  gestion-station-ski:
    build: C:\Users\islem\Downloads\gestion-station-ski
    image: gestion-station-ski
    container_name: gestion-station-ski
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container-devops:3306/stationSki?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    ports:
      - "8089:8089"
    depends_on:
      - mysql-container-devops
    networks:
      - devops-network

networks:
  devops-network:

volumes:
  mysql-data: